config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "site/home#index"

  devise_for :users,
             path: "",
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             },
             path_names: {
               edit: "profile/edit",
               sign_in: "/login",
               sign_out: "/logout"
             }

  namespace :admin do
    root to: redirect("admin/dashboard")

    resources :dashboard, only: :index, constraints: { format: :html }
    resources :categories, param: :slug
    resources :products, param: :slug do
      resources :stocks
    end
    resources :orders, only: %i[index show], param: :order_code do
      member { put :fulfill }
    end
    resources :customers, only: :index
    resources :subscribers, only: :index
  end

  scope module: "site" do
    get "cart" => "cart#show"
    get "order/success" => "checkout#success"
    get "order/cancel" => "checkout#cancel"
    post "checkout" => "checkout#create"
    resources :categories, only: %i[index show], param: :slug
    resources :products, only: %i[index show], param: :slug
    resources :subscribers, only: %i[new create]
    resources :orders, only: %i[index show], param: :order_code
  end

  post "stripe_webhooks" => "webhooks#stripe"
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  include Filterable

  belongs_to :user, inverse_of: :orders

  has_many :order_items, -> { order(:id) }, inverse_of: :order, dependent: :destroy

  broadcasts_refreshes

  validates :order_code, presence: true, uniqueness: { case_sensitive: false }
  validates :customer_email, :customer_full_name, :customer_address, presence: true
  validate :validate_has_one_item

  after_initialize :generate_order_code, if: :new_record?

  scope :datatable,
        -> do
          select(
            "orders.id, orders.order_code, orders.created_at, orders.fulfilled, orders.total,
            CONCAT(users.first_name, ' ', users.last_name) AS customer_full_name"
          ).from("orders JOIN users ON orders.user_id = users.id").order(created_at: :desc)
        end
  scope :recent_unfulfilled, -> { where(fulfilled: false).order(created_at: :desc).take(5) }
  scope :today, -> { where(created_at: Time.current.midnight..Time.current) }
  scope :revenue, -> { today.sum(:total) }
  scope :sales, -> { today.count }
  scope :avg_sale, -> { today.average(:total).to_f }
  scope :per_sale, -> { joins(:order_items).today.average(:quantity).to_i }
  scope :filter_by_order_code, ->(order_code) { where("order_code ILIKE ?", "%#{order_code}%") }
  scope :filter_by_customer,
        ->(customer) { where("CONCAT(users.first_name, ' ', users.last_name) ILIKE ?", "%#{customer}%") }

  def build_order_items(line_items)
    line_items["data"].each do |item|
      product = Stripe::Product.retrieve(item["price"]["product"])
      product_id = product["metadata"]["product_id"].to_i
      stock = Stock.find(product["metadata"]["product_stock_id"])
      order_items.build(
        product_id:,
        stock:,
        product_name: product["name"],
        product_price: item["price"]["unit_amount_decimal"].to_f / 100,
        size: product["metadata"]["size"],
        quantity: item["quantity"]
      )
      stock.update!(quantity: stock.quantity - item["quantity"].to_i)
    end
  end

  def fulfill!
    lock!

    if fulfilled
      errors.add(:order, "#{order_code} is already fulfilled.")
      raise ActiveRecord::RecordInvalid, self
    end
    update!(fulfilled: true)
  end

  private

  def generate_order_code
    epoch_time = Time.current.to_i

    self.order_code = "SL-#{epoch_time}-0#{rand(10)}"
  end

  def validate_has_one_item
    errors.add(:order, "needs at least one item") if order_items.empty?
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  class OrdersController < AdminController
    before_action :set_order, only: %i[show fulfill]

    # GET /admin/orders or /admin/orders.json
    def index
      @orders = Order.datatable.filters(params.slice(:order_code, :customer))
      @pagy, @orders = pagy(@orders, limit: count_per_page)
    end

    # GET /admin/orders/1 or /admin/orders/1.json
    def show
    end

    def fulfill
      @order.fulfill!
      redirect_to admin_order_url(@order), notice: t("record.fulfill", code: @order.order_code)
    rescue ActiveRecord::RecordInvalid => e
      logger.tagged("Fulfill Order Error") { logger.error e.message }
      flash.now[:alert] = e.message
      render :show, status: :unprocessable_content
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order =
        Order
          .joins(:user)
          .includes(:order_items)
          .select(
            "orders.*, users.email AS customer_email,
            CONCAT(users.first_name, ' ', users.last_name) AS customer_full_name"
          )
          .find_by!(order_code: params[:order_code])
    rescue ActiveRecord::RecordNotFound
      logger.error "Order not found #{params[:order_code]}"
      redirect_back(fallback_location: admin_orders_url)
    end
  end
end

app/controllers/site/orders_controller.rb
# frozen_string_literal: true

module Site
  class OrdersController < SiteController
    before_action :check_and_authenticate_user

    def index
      @orders = current_user.orders.filters(params.slice(:order_code)).order(created_at: :desc)
      @pagy, @orders = pagy(@orders, limit: count_per_page)
    end

    def show
      @order = current_user.orders.includes(order_items: :product).find_by!(order_code: params[:order_code])
    rescue ActiveRecord::RecordNotFound
      logger.error "Order not found #{params[:order_code]}"
      redirect_back(fallback_location: orders_url)
    end

    private

    def check_and_authenticate_user
      redirect_to new_user_session_url and return unless user_signed_in?
      redirect_to root_url and return if !current_user.customer?
    end
  end
end

app/views/admin/orders/_content.html.slim
= form_with(url: admin_orders_path, method: "GET",
  data: { turbo_frame: "data-table", controller: "filter", action: "input->filter#submitFilter" }) do |f|
  div class="flex flex-wrap items-center justify-between pb-4"
    div class="flex flex-wrap items-center justify-between"
      div class="mb-1 mr-1"
        label for="order_code-search" class="sr-only" Search
        div class="relative"
          div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none"
            i class="fa-solid fa-magnifying-glass w-4 h-4 text-gray-500 dark:text-gray-400"
          = f.search_field :order_code, value: params[:order_code], id: "order_code-search", class: "ps-10 form-input",
            placeholder: t(".form.search_code_placeholder")
      div class="mb-1"
        label for="customer-search" class="sr-only" Search
        div class="relative"
          div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none"
            i class="fa-solid fa-magnifying-glass w-4 h-4 text-gray-500 dark:text-gray-400"
          = f.search_field :customer, value: params[:customer], id: "customer-search", class: "ps-10 form-input",
            placeholder: t(".form.search_customer_placeholder")
    div class="mb-1"
      select name="count_per_page" class="form-input"
        == items_option_selected
= turbo_frame_tag "data-table", "data-turbo-action": "advance" do
  == render "table"

app/views/admin/orders/_order.html.slim
section id="#{dom_id order}" class="order-section-container"
  div class="p-6 space-y-4 md:space-y-6 sm:p-8"
    div class="grid gap-4 sm:grid-cols-2 sm:gap-6 my-5"
      .w-full
        strong class="strong-label" = "#{t(".status")}:"
        = order_status_badge(order.fulfilled)
      .w-full
        strong class="strong-label" = "#{t(".code")}:"
        span class="text-gray-900 dark:text-white" =< order.order_code
      .w-full
        strong class="strong-label" = "#{t(".date")}:"
        span class="text-gray-900 dark:text-white" = format_date(order.created_at, "%b %e, %Y %l:%M %p")
      .w-full
        strong class="strong-label" = "#{t(".total")}:"
        span class="text-gray-900 dark:text-white" =< number_to_currency(order.total, unit: "$")
      .w-full
        strong class="strong-label" = "#{t(".customer")}:"
        span class="text-gray-900 dark:text-white" =< order.customer_full_name
      .w-full
        strong class="strong-label" = "#{t(".email")}:"
        span class="text-gray-900 dark:text-white" =< order.customer_email
      div class="sm:col-span-2"
        strong class="strong-label" = "#{t(".address")}:"
        span class="text-gray-900 dark:text-white" =< order.customer_address
    == render "order_items_table", order_items: order.order_items
    div
      =< link_to admin_orders_path, class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
        i class="fa-solid fa-arrow-left w-3.5 h-3.5 me-2"
        = t("actions.back_to_resources", resources_name: t("resources.orders"))
      - unless order.fulfilled
        button[data-modal-target="popup-modal" data-modal-toggle="popup-modal" type="button"
          class="btn-success"
        ]
          i class="fa-solid fa-check w-3.5 h-3.5 me-2"
          = t(".actions.fulfill")

        == render "admin/shared/modal", action: "fulfill",
          path: fulfill_admin_order_path(order.order_code), method: :put

app/views/admin/orders/_order_items_table.html.slim
div class="relative overflow-x-auto shadow-md sm:rounded-lg"
  table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
    thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400"
      tr
        th scope="col" class="px-6 py-3"
          = t(".product")
        th scope="col" class="px-6 py-3"
          = t(".size")
        th scope="col" class="px-6 py-3"
          = t(".quantity")
        th scope="col" class="px-6 py-3"
          = t(".price")
        th scope="col" class="px-6 py-3"
          = t(".subtotal")
    tbody
      - order_items.each do |order_item|
        tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
          th scope="row" class="underline px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
            = link_to order_item.product_name, admin_product_path(order_item.product)
          td class="px-6 py-4 whitespace-nowrap"
            = order_item.size
          td class="px-6 py-4 whitespace-nowrap"
            = order_item.quantity
          th class="px-6 py-4 whitespace-nowrap"
            = number_to_currency(order_item.product_price, unit: "$")
          td class="px-6 py-4 whitespace-nowrap"
            = number_to_currency(order_item.subtotal, unit: "$")

app/views/admin/orders/_table.html.slim
div class="relative overflow-x-auto shadow-md sm:rounded-lg"
  table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
    thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400"
      tr
        th scope="col" class="px-6 py-3"
          = t(".code")
        th scope="col" class="px-6 py-3"
          = t(".customer")
        th scope="col" class="px-6 py-3"
          = t(".date")
        th scope="col" class="px-6 py-3"
          = t(".total")
        th scope="col" class="px-6 py-3"
          = t(".status")
    tbody
      - @orders.each do |order|
        = turbo_stream_from order
        tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
          th scope="row" class="underline px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
            = link_to order.order_code, admin_order_path(order.order_code), data: { turbo_frame: :_top }
          td class="px-6 py-4 whitespace-nowrap"
            = order.customer_full_name
          td class="px-6 py-4 whitespace-nowrap"
            = format_date(order.created_at, "%b %e, %Y %l:%M %p")
          td class="px-6 py-4 whitespace-nowrap"
            = number_to_currency(order.total, unit: "$")
          td class="px-6 py-4"
            = order_status_badge(order.fulfilled)
== render "admin/shared/pagination"

app/views/admin/orders/index.html.slim
- title t(".page_title")

.w-full
  h1 class="mb-4 h1-label" = t(".heading")
  == render "content"

app/views/admin/orders/show.html.slim
- title t(".page_title", order_code: @order.order_code)

= turbo_stream_from @order

== render "admin/orders/order", order: @order