config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "site/home#index"

  devise_for :users,
             path: "",
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             },
             path_names: {
               edit: "profile/edit",
               sign_in: "/login",
               sign_out: "/logout"
             }

  namespace :admin do
    root to: redirect("admin/dashboard")

    resources :dashboard, only: :index, constraints: { format: :html }
    resources :categories, param: :slug
    resources :products, param: :slug do
      resources :stocks
    end
    resources :orders, only: %i[index show], param: :order_code do
      member { put :fulfill }
    end
    resources :customers, only: :index
    resources :subscribers, only: :index
  end

  scope module: "site" do
    get "cart" => "cart#show"
    get "order/success" => "checkout#success"
    get "order/cancel" => "checkout#cancel"
    post "checkout" => "checkout#create"
    resources :categories, only: %i[index show], param: :slug
    resources :products, only: %i[index show], param: :slug
    resources :subscribers, only: %i[new create]
    resources :orders, only: %i[index show], param: :order_code
  end

  post "stripe_webhooks" => "webhooks#stripe"
end

app/views/shared/_alert.html.slim
- if alert.present?
  div id="alert-danger" role="alert" class="alert-danger"
    <svg class="shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      path d=("M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1" \
        " 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z")
    </svg>
    span class="sr-only" Info
    div class="ms-3 text-sm font-medium"
      = sanitize(alert, tags: %w[em strong])

app/views/shared/_errors.html.slim
- if errors.any?
  div id="alert-danger" role="alert" class="mt-2 alert-danger"
    <svg class="shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      path d=("M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1" \
        " 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z")
    </svg>
    span class="sr-only" Info
    div class="ms-3 text-sm font-medium"
      ul
        - errors.each do |error|
          li = error

app/views/shared/_flash.html.slim
== render "shared/alert"
== render "shared/notice"
== render "shared/warning"

app/views/shared/_footer.html.slim
footer class="bg-gray-800 text-white"
  div class="max-w-6xl mx-auto px-4 py-10 md:py-20"
    div class="xl:grid xl:grid-cols-3 xl:gap-8"
      <!-- About -->
      div id="about" class="space-y-8 xl:col-span-1"
        h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase"
          = t(".about.label")
        p class="text-white leading-6"
          = t(".about.description")
      <!-- Quick Links -->
      div class="grid grid-cols-2 gap-8 mt-12 xl:mt-0 xl:col-span-2"
        div class="md:grid md:grid-cols-2 md:gap-8"
          div
            h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase"
              = t(".quick_links.label")
            ul class="mt-4 space-y-4"
              li
                = link_to t(".quick_links.home"), root_path, class: "text-base leading-6 text-white hover:text-gray-300"
              li
                = link_to t(".quick_links.github"), "https://github.com/binos30",
                  class: "text-base leading-6 text-white hover:text-gray-300", target: :_blank, rel: :noopener
              li
                = link_to t(".quick_links.facebook"), "https://www.facebook.com/B1NOS",
                  class: "text-base leading-6 text-white hover:text-gray-300", target: :_blank, rel: :noopener
              li
                = link_to t(".quick_links.linkedin"), "https://www.linkedin.com/in/binos30",
                  class: "text-base leading-6 text-white hover:text-gray-300", target: :_blank, rel: :noopener
              li
                = link_to t(".quick_links.source_code"), "https://github.com/binos30/shopline",
                  class: "text-base leading-6 text-white hover:text-gray-300", target: :_blank, rel: :noopener
      <!-- Contact Info -->
      div class="md:grid md:grid-cols-2 md:gap-8 my-8"
        div
          h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase"
            = t(".contact.label")
          ul class="mt-4 space-y-4"
            li
              p class="text-base leading-6 text-white" 123 Shopline Center
            li
              p class="text-base leading-6 text-white" = "#{t(".contact.email")}: support@shopline.com"
            li
              p class="text-base leading-6 text-white" = "#{t(".contact.phone")}: 123-456"
      div class="border-t border-gray-700"
        div class="py-8 text-center"
          p class="text-base leading-6 text-gray-400 md:order-1"
            | Life is a gift, and the Giver is good.
            br/
            | Glory is all His &#9757;
            br/
            | &copy; #{local_time(Time.current, "%Y")} Shopline. All rights reserved.

app/views/shared/_google_tag.html.slim
- if Rails.env.production?
  /! Google tag (gtag.js)
  script[async src="https://www.googletagmanager.com/gtag/js?id=G-HXY81TL7EB"]
  javascript[nonce=request.content_security_policy_nonce]:
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-HXY81TL7EB');

app/views/shared/_meta_tags.html.slim
- title = content_for?(:title) ? yield(:title) : t(:title)
- description = "Shopline is a leading online marketplace, offering a wide range of products to cater to all your needs."

meta name="author" content="Venus Lumanglas"
meta name="description" content="#{description}"
meta name="keywords" content="shopline, shopping, marketplace, e-commerce, ecommerce, online store"

<!-- Facebook Open Graph data -->
meta property="og:type" content="website"
meta property="og:url" content="#{request.original_url}"
meta property="og:title" content="#{title}"
meta property="og:description" content="#{description}"
meta property="og:image" content="#{image_url("homepage.png")}"

<!-- Twitter Card data -->
meta name="twitter:card" content="summary"
meta name="twitter:url" content="#{request.original_url}"
meta name="twitter:title" content="#{title}"
meta name="twitter:description" content="#{description}"
meta name="twitter:image" content="#{image_url("homepage.png")}"

app/views/shared/_navbar.html.slim
nav class="bg-white fixed w-full z-40 top-0 start-0 border-b border-gray-200"
  div class="max-w-(--breakpoint-xl) flex flex-wrap items-center justify-between mx-auto p-4"
    = link_to root_path, class: "flex items-center space-x-3 rtl:space-x-reverse" do
      = image_tag "logo-no-background.svg", class: "h-8", alt: "Shopline Logo"
      span class="self-center text-2xl font-semibold whitespace-nowrap" = t(:title)
    div class="flex items-center md:order-2 gap-2 rtl:space-x-reverse"
      = link_to cart_path, class: "text-gray-500 hover:text-gray-600 me-3 md:me-4" do
        div class="relative py-2"
          div class="t-0 absolute left-3"
            p id="cart-count" class="flex h-2 w-2 items-center justify-center rounded-full bg-red-500 p-3 text-xs text-white"
              | 0
          i class="fa-solid fa-cart-shopping mt-4 h-6 w-6"
      - if user_signed_in?
        button[type="button" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
          data-dropdown-placement="bottom"
          class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 cursor-pointer"
        ]
          span class="sr-only" Open user menu
          = image_tag avatar, class: "w-8 h-8 rounded-full", alt: "user photo"
        <!-- Dropdown menu -->
        div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow-sm" id="user-dropdown"
          div class="px-4 py-3"
            span class="block text-sm text-gray-900" = current_user.full_name
            span class="block text-sm  text-gray-500 truncate" = current_user.email
          ul class="py-2" aria-labelledby="user-menu-button"
            - if current_user.admin?
              li
                = link_to t(".dashboard"), admin_dashboard_index_path,
                  class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            - if current_user.customer?
              li
                = link_to t(".my_orders"), orders_path,
                  class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            li
              = link_to t(".edit_profile"), edit_user_registration_path,
                class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            li
              = link_to t(".sign_out"), destroy_user_session_path,
                data: { turbo_method: :delete, turbo_confirm: t("turbo.confirm_sign_out") },
                class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
      button[data-collapse-toggle="navbar-items" type="button" aria-controls="navbar-items" aria-expanded="false"
        class=("inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden" \
              " hover:bg-gray-100 focus:outline-hidden focus:ring-2 focus:ring-gray-200")
      ]
        span class="sr-only" Open main menu
        svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14"
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
    div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-items"
      ul id="navbar-links"
        li
          = link_to t(".home"), root_path, nav_link_attributes("home")
        li
          = link_to t(".categories"), categories_path, nav_link_attributes("categories")
        li
          = link_to t(".products"), products_path, nav_link_attributes("products")
        li
          = link_to t(".about"), "#{root_path}#about", nav_link_attributes("about")
        - unless user_signed_in?
          li
            = link_to t(".sign_in"), new_user_session_path,
              class: "block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0"
          li
            = link_to t(".sign_up"), new_user_registration_path,
              class: "block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0"

app/views/shared/_notice.html.slim
- if notice.present?
  div id="alert-success" role="alert" class="alert-success"
    <svg class="shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      path d=("M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1" \
        " 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z")
    </svg>
    span class="sr-only" Info
    div class="ms-3 text-sm font-medium"
      = sanitize(notice, tags: %w[em strong])

app/views/shared/_product_image_gallery.html.slim
div class="grid gap-4"
  div id="gallery" class="relative w-full" data-carousel="static"
    /! Carousel wrapper
    div class="relative h-56 overflow-hidden rounded-lg md:h-96"
      - images.each do |image|
        div[data-carousel-item class="hidden duration-700 ease-in-out"]
          = custom_image_tag(image,
            class: "absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2", alt: "Product")
    /! Slider controls
    button[data-carousel-prev type="button"
      class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-hidden"
    ]
      span[
        class=("inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30" \
          " group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white" \
          " dark:group-focus:ring-gray-800/70 group-focus:outline-hidden")
      ]
        svg[
          class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 6 10"
        ]
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
        <span class="sr-only">Previous</span>
    button[data-carousel-next type="button"
      class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-hidden"
    ]
      span[
        class=("inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30" \
          " group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white" \
          " dark:group-focus:ring-gray-800/70 group-focus:outline-hidden")
      ]
        svg[
          class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 6 10"
        ]
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
        <span class="sr-only">Next</span>

  div class="grid grid-cols-5 gap-4"
    - images.each do |image|
      div
        = custom_image_tag(image, class: "h-auto max-w-full rounded-lg", alt: "Product")

app/views/shared/_warning.html.slim
- if !defined?(warning).nil? && warning.present?
  div id="alert-warning" role="alert" class="alert-warning"
    <svg class="shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      path d=("M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1" \
        " 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z")
    </svg>
    span class="sr-only" Info
    div class="ms-3 text-sm font-medium"
      = sanitize(warning, tags: %w[em strong])