config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "site/home#index"

  devise_for :users,
             path: "",
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             },
             path_names: {
               edit: "profile/edit",
               sign_in: "/login",
               sign_out: "/logout"
             }

  namespace :admin do
    root to: redirect("admin/dashboard")

    resources :dashboard, only: :index, constraints: { format: :html }
    resources :categories, param: :slug
    resources :products, param: :slug do
      resources :stocks
    end
    resources :orders, only: %i[index show], param: :order_code do
      member { put :fulfill }
    end
    resources :customers, only: :index
    resources :subscribers, only: :index
  end

  scope module: "site" do
    get "cart" => "cart#show"
    get "order/success" => "checkout#success"
    get "order/cancel" => "checkout#cancel"
    post "checkout" => "checkout#create"
    resources :categories, only: %i[index show], param: :slug
    resources :products, only: %i[index show], param: :slug
    resources :subscribers, only: %i[new create]
    resources :orders, only: %i[index show], param: :order_code
  end

  post "stripe_webhooks" => "webhooks#stripe"
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Filterable
  include Sluggable

  # Set the attribute from which the slug would be generated
  slugify :name

  belongs_to :category, inverse_of: :products

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end
  has_many :stocks, inverse_of: :product, dependent: :destroy
  has_many :order_items, inverse_of: :product, dependent: :restrict_with_exception

  has_rich_text :description

  broadcasts_refreshes_to :category
  broadcasts_refreshes

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :price, presence: true, numericality: { in: 0..999_999_999 }
  validates :images, content_type: %i[jpeg jpg png webp], size: { less_than_or_equal_to: 3.megabytes }

  scope :available, -> { joins(:stocks).where("quantity > 0").distinct }
  scope :filter_by_name, ->(name) { where("name ILIKE ?", "%#{name}%") }
  scope :filter_by_min, ->(min) { where(price: min..) }
  scope :filter_by_max, ->(max) { where(price: ..max) }
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < AdminController
    before_action :set_lookups, only: %i[new create edit update]
    before_action :set_product, only: %i[update destroy]

    # GET /admin/products or /admin/products.json
    def index
      @products =
        Product.filters(params.slice(:name)).includes([:category, { images_attachments: :blob }]).order(:name)
      @pagy, @products = pagy(@products, limit: count_per_page)
    end

    # GET /admin/products/1 or /admin/products/1.json
    def show
      @product =
        Product.includes([:rich_text_description, { images_attachments: :blob }]).find_by_friendly_id(
          params[:slug]
        )
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit
      @product =
        Product.includes([:rich_text_description, { images_attachments: :blob }]).find_by_friendly_id(
          params[:slug]
        )
    end

    # POST /admin/products or /admin/products.json
    def create # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html do
            redirect_to admin_product_url(@product),
                        notice: t("record.create", resource_name: t("resources.product"), name: @product.name)
          end
          format.json { render :show, status: :created, location: admin_product_url(@product) }
        else
          format.html { render :new, status: :unprocessable_content }
          format.json { render json: @product.errors, status: :unprocessable_content }
        end
      end
    rescue ActiveRecord::RecordNotUnique => e
      @product.errors.add(:base, e)
      respond_to do |format|
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @product.errors, status: :unprocessable_content }
      end
    end

    # PATCH/PUT /admin/products/1 or /admin/products/1.json
    def update # rubocop:disable Metrics/AbcSize
      respond_to do |format|
        if @product.update(product_params)
          format.html do
            redirect_to admin_product_url(@product),
                        notice: t("record.update", resource_name: t("resources.product"), name: @product.name)
          end
          format.json { render :show, status: :ok, location: admin_product_url(@product) }
        else
          format.html { render :edit, status: :unprocessable_content }
          format.json { render json: @product.errors, status: :unprocessable_content }
        end
      end
    rescue ActiveRecord::RecordNotUnique => e
      @product.errors.add(:base, e)
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @product.errors, status: :unprocessable_content }
      end
    end

    # DELETE /admin/products/1 or /admin/products/1.json
    def destroy # rubocop:disable Metrics/AbcSize
      @product.destroy!

      respond_to do |format|
        format.html do
          redirect_to admin_products_url,
                      notice: t("record.delete", resource_name: t("resources.product"), name: @product.name)
        end
        format.json { head :no_content }
      end
    rescue ActiveRecord::DeleteRestrictionError, ActiveRecord::InvalidForeignKey => e
      logger.tagged("Delete Product##{@product.id} Error") { logger.error e }
      redirect_to admin_products_url, alert: e
    end

    private

    def set_lookups
      @categories = Category.active.order(:name)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_friendly_id(params[:slug])
    rescue ActiveRecord::RecordNotFound
      logger.error "Product not found #{params[:slug]}"
      redirect_back(fallback_location: admin_products_url)
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params
        .require(:product)
        .permit(:name, :description, :price, :active, :category_id, images: [])
        .each_value { |value| value.try(:strip!) }
    end
  end
end

app/controllers/site/products_controller.rb
# frozen_string_literal: true

module Site
  class ProductsController < SiteController
    def index
      @products =
        Product
          .includes(images_attachments: :blob)
          .filters(params.slice(:name, :min, :max))
          .available
          .active
          .order(:name)
      @pagy, @products = pagy(:countless, @products, limit: 10)

      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    def show
      @product =
        Product
          .includes([:rich_text_description, :stocks, { images_attachments: :blob }])
          .active
          .find_by_friendly_id(params[:slug]) # rubocop:disable Rails/DynamicFindBy
      @product_data = @product.as_json(only: %i[id name price slug])
    rescue ActiveRecord::RecordNotFound
      logger.error "Product not found #{params[:slug]}"
      redirect_back(fallback_location: root_url)
    end
  end
end

app/views/admin/products/_content.html.slim
= form_with(url: admin_products_path, method: "GET",
  data: { turbo_frame: "data-table", controller: "filter", action: "input->filter#submitFilter" }) do |f|
  div class="flex flex-wrap items-center justify-between pb-4"
    div class="mb-1"
      label for="name-search" class="sr-only" Search
      div class="relative"
        div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none"
          i class="fa-solid fa-magnifying-glass w-4 h-4 text-gray-500 dark:text-gray-400"
        = f.search_field :name, value: params[:name], id: "name-search", placeholder: t(".form.search_placeholder"),
          class: "ps-10 form-input"
    div class="mb-1"
      select name="count_per_page" class="form-input"
        == items_option_selected
= turbo_frame_tag "data-table", "data-turbo-action": "advance" do
  == render "table"

app/views/admin/products/_form.html.slim
- submit_label = product.new_record? ? t(".create") : t(".update")

section class="section-container"
  div class="p-6 space-y-4 md:space-y-6 sm:p-8"
    h1 class="h1-label" = product.id? ? t(".heading.edit") : t(".heading.new")
    = form_with(model: [:admin, product], class: "contents") do |form|
      == render "shared/errors", errors: product&.errors&.full_messages || []
      div class="grid gap-4 sm:grid-cols-2 sm:gap-6 my-5"
        .w-full
          = form.label :active, class: "inline-flex items-center cursor-pointer"
            = form.check_box :active, class: "sr-only peer"
            span class="text-sm font-medium text-gray-900 dark:text-white" = t(".status")
            div class="peer form-switch"
        div class="sm:col-span-2"
          = form.label :name, t(".name"), class: "form-label"
          = form.text_field :name, required: true, placeholder: "Product 1",
            class: "form-input"
        .w-full
          = form.label :category_id, t(".category"), class: "form-label"
          = form.collection_select(:category_id, @categories, :id, :name,
            { include_blank: "Select a Category" }, required: true,
            class: "form-input")
        .w-full
          = form.label :price, t(".price"), class: "form-label"
          = form.number_field :price, min: "0", max: "999999999", step: ".01", required: true, placeholder: "0.0",
            class: "form-input"
        div class="sm:col-span-2"
          = form.label :images, t(".images"), class: "form-label"
          - if product.images.attached?
            div class="grid grid-cols-3 md:grid-cols-4 gap-2 mb-2"
              - product.images.each do |image|
                - if image.persisted?
                  div
                    = custom_image_tag(image, class: "w-20 h-20 object-cover rounded-md")
                    = form.hidden_field :images, multiple: true, value: image.signed_id, id: nil
          = form.file_field :images, multiple: true, accept: "image/*",
            class: "form-input"
        div class="sm:col-span-2"
          = form.label :description, t(".description"), class: "form-label"
          = form.rich_text_area :description, placeholder: "Your description here",
            class: "form-input"
      = form.submit submit_label, class: "btn-primary"
    div
      - if product.id?
        => link_to admin_product_stocks_path(product), class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
          i class="fa-solid fa-boxes-stacked w-3.5 h-3.5 me-2"
          = t(".actions.show_product_stocks")
        => link_to admin_product_path(product), class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
          i class="fa-solid fa-eye w-3.5 h-3.5 me-2"
          = t("actions.show_resource", resource_name: t("resources.product"))
      =< link_to admin_products_path, class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
        i class="fa-solid fa-arrow-left w-3.5 h-3.5 me-2"
        = t("actions.back_to_resources", resources_name: t("resources.products"))

app/views/admin/products/_product.html.slim
section id="#{dom_id product}" class="section-container"
  div class="p-6 space-y-4 md:space-y-6 sm:p-8"
    p
      strong class="strong-label" = "#{t(".status")}:"
      = status_badge(product.active)
    p
      strong class="strong-label" = "#{t(".category")}:"
      span class="text-gray-900 dark:text-white" =< product.category.name
    p
      strong class="strong-label" = "#{t(".name")}:"
      span class="text-gray-900 dark:text-white" =< product.name
    div
      strong class="strong-label" = "#{t(".description")}:"
      span class="text-gray-900 dark:text-white"
        = product.description
    p
      strong class="strong-label" = "#{t(".price")}:"
      span class="text-gray-900 dark:text-white" =< number_to_currency(product.price, unit: "$")
    - if product.images.attached?
      = render partial: "shared/product_image_gallery", locals: { images: product.images }
    div
      => link_to edit_admin_product_path(product), class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
        i class="fa-solid fa-pen w-3.5 h-3.5 me-2"
        = t("actions.edit_resource", resource_name: t("resources.product"))
      =< link_to admin_products_path, class: "btn-dark border border-gray-300 dark:border-gray-700 me-2 mb-2" do
        i class="fa-solid fa-arrow-left w-3.5 h-3.5 me-2"
        = t("actions.back_to_resources", resources_name: t("resources.products"))
      button[data-modal-target="popup-modal" data-modal-toggle="popup-modal" type="button"
        class="btn-danger border border-red-300 dark:border-red-700 me-2 mb-2"
      ]
        i class="fa-solid fa-trash w-3.5 h-3.5 me-2"
        = t("actions.destroy_resource", resource_name: t("resources.product"))

== render "admin/shared/modal", resource_name: t("resources.product"), path: admin_product_path(product)

app/views/admin/products/_table.html.slim
div class="relative overflow-x-auto shadow-md sm:rounded-lg"
  table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
    thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400"
      tr
        th scope="col" class="px-6 py-3"
          = t(".image")
        th scope="col" class="px-6 py-3"
          = t(".name")
        th scope="col" class="px-6 py-3"
          = t(".category")
        th scope="col" class="px-6 py-3"
          = t(".price")
        th scope="col" class="px-6 py-3"
          = t(".status")
    tbody
      - @products.each do |product|
        = turbo_stream_from product
        tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
          td class="px-6 py-4"
            - if product.images.attached?
              = custom_image_tag(product.images.first, variant: :thumb, width: 50, height: 50)
            - else
              = image_tag("https://placehold.co/50")
          th scope="row" class="underline px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
            = link_to product.name, edit_admin_product_path(product), data: { turbo_frame: :_top }
          td class="px-6 py-4 whitespace-nowrap"
            = product.category.name
          td class="px-6 py-4 whitespace-nowrap"
            = number_to_currency(product.price, unit: "$")
          td class="px-6 py-4"
            = status_badge(product.active)
== render "admin/shared/pagination"

app/views/admin/products/edit.html.slim
- title t(".page_title", product_id: @product.id)

div class="mx-auto w-full"
  == render "form", product: @product

app/views/admin/products/index.html.slim
- title t(".page_title")

.w-full
  .flex.justify-between.items-center.mb-4
    h1 class="h1-label" = t(".heading")
    = link_to new_admin_product_path, class: "btn-primary" do
      i class="fa-solid fa-plus w-3.5 h-3.5 me-2"
      = t("actions.new_resource", resource_name: t("resources.product"))
  == render "content"

app/views/admin/products/new.html.slim
- title t(".page_title")

div class="mx-auto w-full"
  == render "form", product: @product

app/views/admin/products/show.html.slim
- title t(".page_title", product_id: @product.id)

= turbo_stream_from @product

== render "admin/products/product", product: @product